name: SalesReceipt Workflow

on: [push]

jobs:
    build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
   
    test:
    
      runs-on: [ubuntu-latest]

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Test with mstest
        run: dotnet test --configuration Release
      
    run:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Run program with dotnet
        run: dotnet run --project "./SalesReceiptApp/SalesReceiptApp.csproj" --configuration Release
   
    publish:
        
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 2.2.108
        - name: Build with dotnet
          run: dotnet build --configuration Release
        - name: Upload artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            # Artifact name
            name: SalesReceipt Library
            # Directory containing files to upload
            path: ./SalesReceipt/bin/Release/netcoreapp2.2/SalesReceipt.dll
      

